require("rayct.plugins-setup")
require("rayct.core.options")
require("rayct.core.keymaps")
require("rayct.core.colorscheme")
require("rayct.plugins.comment")
require("rayct.plugins.nvim-tree")
require("rayct.plugins.lualine")
require("rayct.plugins.telescope")
-- require("rayct.plugins.nvim-cmp")
-- require("rayct.plugins.lsp.mason")
-- require("rayct.plugins.lsp.lspsaga")
-- require("rayct.plugins.lsp.lspconfig")
-- require("rayct.plugins.lsp.null-ls")
-- require("rayct.plugins.autopairs")
-- require("rayct.plugins.treesitter")
-- require("rayct.plugins.gitsigns")
